### ISSUE TITLE
Character \x00 in to_ascii() raises an exception

### ISSUE THREAD

**Issue by philippemilink** [yamatt/homoglyphs#6]
```py
import homoglyphs as hg
hg.Homoglyphs(languages={'en'}, strategy=hg.STRATEGY_LOAD).to_ascii('\x00')
```
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "homoglyphs/core.py", line 240, in to_ascii
    return self.uniq_and_sort(self._to_ascii(text))
  File "homoglyphs/core.py", line 169, in uniq_and_sort
    result = list(set(data))
  File "homoglyphs/core.py", line 235, in _to_ascii
    for variant in self._get_combinations(text, ascii=True):
  File "homoglyphs/core.py", line 218, in _get_combinations
    alt_chars = self._get_char_variants(char)
  File "homoglyphs/core.py", line 195, in _get_char_variants
    if not self._update_alphabet(char):
  File "homoglyphs/core.py", line 182, in _update_alphabet
    category = Categories.detect(char)
  File "homoglyphs/core.py", line 66, in detect
    category = unicodedata.name(char).split()[0]
ValueError: no such name
```
I guess it should rather return `[]`.

(BTW, is this fork still maintained?)

**Comment by wesinator** [comment]
This exception occurs in the Python standard library unicodedata module:
```python
import unicodedata
print(unicodedata.name("\x00"))
```

there are other similar zero characters that also raise an exception. This seems odd since there seems to be a name alias defined in https://www.unicode.org/Public/15.0.0/ucd/Index.txt

However, the issue in this library is that it's catching the wrong exception type: https://github.com/yamatt/homoglyphs/blob/fe302e55a30d4ef19f8d912241b18855911df858/homoglyphs_fork/core.py#L67
Should be `ValueError`

[NO_TRAIN]::
